[package]
name = "ncae-tool"
version = "0.2.1"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/achievement18/NCAE-Audio-Converter"
description = "NetEase NCAE audio effect reverse-encryption core and CLI"

[[bin]]
name = "ncae-tool-multiformat"
path = "src/main.rs"

[[bin]]
name = "ncae-gui-multiformat"
path = "src/bin/ncae-gui.rs"

[dependencies]
anyhow = "1.0.104"
flate2 = "1.1.10"
serde_json = "1.0.151"
eframe = { version = "0.36.2", default-features = false, features = ["glow"] }
egui = "0.36.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_Controls_Dialogs", "Win32_Foundation", "Win32_System_Registry", "Win32_UI_Shell", "Win32_System_Com"] }
